### ISSUE TITLE
Dosen't work with storybook/html

### ISSUE THREAD

**Issue by neginbasiri** [echoulen/storybook-addon-styled-component-theme#1]
My story .js file

```js
import { storiesOf } from '@storybook/html';
import { withThemesProvider } from 'storybook-addon-styled-component-theme';
import header from '../../templates/partials/header.html';
import '../../styles/partials/index.scss';

const defaultTheme = {
	name: 'Green',
	backgroundColor: 'green',
	textColor: 'white'
};

const darkTheme = {
	name: 'Red',
	backgroundColor: 'red',
	textColor: 'white'
};

const getAllThemes = () => [defaultTheme, darkTheme];

storiesOf('Simple Header', module)
	.addDecorator(withThemesProvider(getAllThemes()))
	.add('Header', () => header);

```

My addons.js
```js
import 'storybook-addon-styled-component-theme/dist/register';
```

Error

`
ERROR in ./node_modules/storybook-addon-styled-component-theme/dist/ThemesProvider.js
Module not found: Error: Can't resolve 'styled-components' in 'C:\Projects\LCA\UI\node_modules\storybook-addon-styled-component-theme\dist'
`

Versions:

 "@storybook/html": "^4.0.0-alpha.16",
   "storybook-addon-styled-component-theme": "^1.0.3",

**Comment by echoulen** [comment]
peer dependencies are
`@storybook/addons`
`react`
`styled-components`

yarn install by yourself
