### ISSUE TITLE
Remember theme selection

### ISSUE THREAD

**Issue by andrewstaker** [echoulen/storybook-addon-styled-component-theme#10]
First of all, this is a great plugin!

Do you have any plans to include the theme selection as a query string in the url? So the selected theme will persist when changing components and also allow linking to different themes.

**Comment by robertwbradford** [comment]
I just installed v1.3.0 with storybook v6, and I'm not seeing the theme selection persist when changing stories. Not sure if this is an issue with this package or storybook v6. My setup:

```
// .storybook/preview.js
import { withThemesProvider } from "storybook-addon-styled-component-theme";

const myThemes = [
  { name: "Default", ... },
  { name: "Another", ...},
  { name: "Yet Another", ...}
];

export const decorators = [
  withThemesProvider(myThemes),
];
```
The panel works great, and I'm able to switch themes within a story. However, when changing to a different story it resets the selected theme.

**Comment by timurcatakli** [comment]
Plus one...
