### ISSUE TITLE
Question: How can I use the theme toggle with a GlobalStyle decorator?

### ISSUE THREAD

**Issue by 1cytel** [echoulen/storybook-addon-styled-component-theme#14]
Hey, First of all - thanks for your awesome plugin!
I do not know if this is possible, maybe someone can give me advice.
I am using a decorator to add my GlobalStyles to storybook like so:

```
// .storybook/config.js
import { configure } from '@storybook/react'
import { addDecorator } from '@storybook/react';
import { withThemesProvider } from 'storybook-addon-styled-component-theme'
import { getTheme } from '../theme/index'
import { ThemeProvider } from 'styled-components'
import GlobalStyles from '../theme/GlobalStyles'

const themes = [getTheme('light'), getTheme('dark')]

addDecorator(withThemesProvider(themes))

function withGlobalStyles(storyFn) {
  return (
    <React.Fragment>
      <ThemeProvider theme={themes[0]}>
        <GlobalStyles />
      </ThemeProvider>
      {storyFn()}
    </React.Fragment>
  )
}

addDecorator(withGlobalStyles)

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /.stories.js$/)
function loadStories () {
  req.keys().forEach(filename => req(filename))
}

configure(loadStories, module)
```
As you can see, I hardcoded the theme into the ```ThemeProvider```.
Is there a way to get the 'active' theme from the plugin in the decorator function?

**Comment by echoulen** [comment]
duplicate with https://github.com/echoulen/storybook-addon-styled-component-theme/blob/master/src/ThemesProvider.tsx#L22

```
function withGlobalStyles(storyFn) {
  return (
    <React.Fragment>
      <GlobalStyles />
      {storyFn()}
    </React.Fragment>
  )
}

addDecorator(withGlobalStyles)
addDecorator(withThemesProvider(themes))
```

may be helpful

**Comment by 1cytel** [comment]
Hey, Sorry for the late response.
Maybe I need to clarify more: I want to use theme properties in the GlobalStyles component.
I tried your suggested method, but the theme prop is not passed down to the GlobalStyle component. Also if I change the order of the decorators like in your example the theme does not get passsed down even with my hardcoded version...

**Comment by slestang** [comment]
I stubble into the same issue and the answer is actually very simple. As stated into styled-components [createGlobalStyle docs](https://www.styled-components.com/docs/api#createglobalstyle), the `theme` props is accessible like in any other styled-components components:

```js
 export default createGlobalStyle`
   body {
    --main-color: ${props => props.theme.mainColor};
   }
```

**Comment by 1cytel** [comment]
@slestang Thanks! Will try it today :)
