### ISSUE TITLE
dist folder not included in package

### ISSUE THREAD

**Issue by akadop** [echoulen/storybook-addon-styled-component-theme#18]
version 1.2.0 introduced a change that resulted in no dist folder being included in the npm package.

opening a pr to fix this

**Comment by akadop** [comment]
seems like i can't create a branch to PR this in..

you need to emit the files TS generates... otherwise you will have no dist folder

**Comment by pollen8** [comment]
I've opened a pull request with what I think is the correct tsconfig change : https://github.com/echoulen/storybook-addon-styled-component-theme/pull/19

**Comment by echoulen** [comment]
Thank you @akadop 
I will fix asap
