### ISSUE TITLE
Emotion support

### ISSUE THREAD

**Issue by nickmccurdy** [echoulen/storybook-addon-styled-component-theme#2]
Would it be possible to use this with Emotion without totally reworking it? They have a similar ThemeProvider: https://emotion.sh/docs/theming

**Comment by echoulen** [comment]
Emotion is not a styled-components library, this is the different topic.

**Comment by patrickgordon** [comment]
I've created a library for this. It works but there's a few things that need fixing. 
https://github.com/JumboInteractiveLimited/storybook-addon-emotion-theme

Thanks to @echoulen for the hard work done already on storybook-addon-styled-component-theme.

:tada: open source software yay.
