### ISSUE TITLE
Does it work for Vue? What should be passed to withThemesProvider?

### ISSUE THREAD

**Issue by tylertrotter** [echoulen/storybook-addon-styled-component-theme#23]
I have 2 questions that remain after reading the readme:

- Can I expect this to work in Vue?
- What do theme1 and theme2 look like in the below example?

```
const themes = [theme1, theme2];
addDecorator(withThemesProvider(themes));
```
Are they JS objects? HTML els with styles? Or, something else?

**Comment by echoulen** [comment]
reply to @tylertrotter 
- 1. not yet, contributing welcome !
- 2. https://www.styled-components.com/docs/advanced
