### ISSUE TITLE
I cannot open the iframe url i get id=undefined

### ISSUE THREAD

**Issue by LennardWesterveld** [echoulen/storybook-addon-styled-component-theme#24]
Hi there,

Maybe some one knows a solution that you cannot open a iframe url? this is used for example to embed it somewhere else on a website. What i noticed is that the id says id=undefined in the  development console. If i remove the storybook addon everything works fine but if i add it i get a blanco page when i trying to open the iframe.html?id=VALIDID 

Does some one have also those issues?

Kind regards

**Comment by echoulen** [comment]
no support iframe

**Comment by austb25** [comment]
Any chance this can be supported @echoulen ? It is the only thing stopping me from using this addon 😭
