### ISSUE TITLE
withThemesProvider global decorator breaks storyshot snapshots

### ISSUE THREAD

**Issue by jwm0** [echoulen/storybook-addon-styled-component-theme#27]
### Description
It appears that using a global decorator will break the snapshots generated by jest + storyshots. The result of each snapshot will be `null`

Example:
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Storyshots @components/atoms/Button Primary 1`] = `null`;

exports[`Storyshots @components/atoms/Button Secondary 1`] = `null`;

```

I tried experimenting with the storyshots and babel config itself but nothing seems to be working. 

### Steps to reproduce
Clone a sample storybook + snapshots repo (like this one: https://github.com/solepano/storybook-sample) and add `withThemeProviders` decorator.

**Comment by echoulen** [comment]
https://github.com/solepano/storybook-sample/blob/master/package.json never use the library, please make sure you post to the right repository

**Comment by jamesg1** [comment]
Without jest support it makes this plugin tough to use?

**Comment by Lange** [comment]
I have this problem as well. I tried ensuring that my `addDecorator` call was running before my `require.context` call, as suggested in some of the links off of @jamesg1's comment, but I still can't get it to work.

**Comment by kevinhaas** [comment]
I'm still seeing the issue referenced here https://github.com/storybookjs/storybook/issues/5803

**Comment by goozo** [comment]
@ghost @jwm0 did you find a solution? I am also seeing this issue also with storyshots.
