### ISSUE TITLE
addDecorator question.

### ISSUE THREAD

**Issue by PaulieScanlon** [echoulen/storybook-addon-styled-component-theme#28]
Hey, i love this addon it's really great. My config is as follows

```
addDecorator(withThemesProvider(themes));
```

Which works great but i'd also like to add something like this

```
addDecorator(story => <Main>{story}</Main>)
```

and have main also respond to the theme changes when the UI buttons are clicked... but if i do it this way `Main` as a decorator has no access to the theme... any ideas?

As a work around i've done this

```
const stories = storiesOf("Buttons/ButtonAction", module).addDecorator(
  story => <Main>{story()}</Main>
);

stories.add("usage", () => <ButtonAction>Button Action</ButtonAction>, {
  info: "This is a buttonAction"
});

```

which works fine but `Main` will show up in my story source which is kinda not what i want.

![Screenshot 2019-06-17 at 10 37 42](https://user-images.githubusercontent.com/1465706/59594579-00b42b80-90ec-11e9-94ba-650280efde2e.png)

**Comment by echoulen** [comment]
soruce code
``` tsx
export const withThemesProvider = (themes: Theme[]) => (story): JSX.Element => {
  return <ThemesProvider themes={List(themes)}>{story()}</ThemesProvider>;
};
```

try to custom your decorator

``` tsx
import ThemesProvider from "storybook-addon-styled-component-theme";
import {List} from "immutable"

export const withCustomThemesProvider = (themes: Theme[]) => (story): JSX.Element => {
  return <ThemesProvider themes={List(themes)}><!-- custom here --></ThemesProvider>;
};

```
