### ISSUE TITLE
Does not look good for storybook 5.1.9

### ISSUE THREAD

**Issue by fooloomanzoo** [echoulen/storybook-addon-styled-component-theme#29]
In storybook `5.1.9` a style is appliedto the Selectors, that overflows the area:

![image](https://user-images.githubusercontent.com/9318952/59861847-ded3d680-9381-11e9-8a0e-84c08d96479d.png)

**Comment by petemill** [comment]
This was merged, and published to github as v1.2.4, but not to npm, which is still at v1.2.3. Any chance of a publish please?

**Comment by jamesg1** [comment]
@echoulen Hi likewise to @petemill could we get 1.2.4 released to npm?
