### ISSUE TITLE
RowStyle not getting applied

### ISSUE THREAD

**Issue by benjamingeorge** [echoulen/storybook-addon-styled-component-theme#31]
Just loaded up this addon and noticed RowStyle css is not getting applied, resulting in stretched buttons.  
<img width="208" alt="Screen Shot 2019-07-14 at 12 02 21 PM" src="https://user-images.githubusercontent.com/1595732/61186871-f83e0a80-a62f-11e9-9319-2b51bf1acde3.png">

**Comment by echoulen** [comment]
can show your storybook and storybook-addon-styled-component-theme version?

**Comment by benjamingeorge** [comment]
it is v1.2.3

**Comment by echoulen** [comment]
try to use 1.2.4
https://github.com/echoulen/storybook-addon-styled-component-theme/releases/tag/v1.2.4

**Comment by benjamingeorge** [comment]
yes that works.  can you please push to NPM this version?
