### ISSUE TITLE
Possible to pass own wrapper?

### ISSUE THREAD

**Issue by sami616** [echoulen/storybook-addon-styled-component-theme#32]
Hi there, is it possible to pass my own custom theme wrappers instead of just a theme object? Reason for this being that I also want to pass some global styles for each theme too?

Ie

```
<MyTheme>
     <GlobalStyles/>
     {children}
</MyTheme>
```

**Comment by sami616** [comment]
I have tweaked the library to accept an object of wrappers instead of theme objects for my own use case. If anyone is looking for a solution like this let me know:

ie:
```
addDecorator(
  withThemesProvider({
     "Theme one": ThemeOne,
     "Theme two": ThemeTwo,
  })
)

```

**Comment by FedericoLaggiard** [comment]
> I have tweaked the library to accept an object of wrappers instead of theme objects for my own use case. If anyone is looking for a solution like this let me know:
> 
> ie:
> 
> ```
> addDecorator(
>   withThemesProvider({
>      "Theme one": ThemeOne, // <-- React Components that render children
>      "Theme two": ThemeTwo, 
>   })
> )
> ```

Can you please elaborate? I have the same issue with GloblStyle and I'm looking for a solution.

Thanks!

**Comment by sami616** [comment]
Sure, i basically tweaked this library to accept components instead of theme objects for my own use case. Will turn this into an npm module or submit a PR to this repo if i get time, but in the meantime i'm happy to share my solution if you connect with me via twitter @samiresua616

**Comment by yannbf** [comment]
I'm experiencing the same thing, would like to be able to set the background color of the story wrapper so that dark mode makes more sense. Right now when I set dark mode on, the text becomes white but the body of the story does not change color, hence I get a "white screen"

**Comment by terotic** [comment]
This worked for me. You can also just add another decorator before `withThemesProvider`. 

```
addDecorator(storyFN => <GlobalStyles>{storyFN()}</GlobalStyles>);
addDecorator(withThemesProvider(themes));
```

Used styled-components `createGlobalStyle` in GlobalStyles-wrapper to add theme on the global style.
