### ISSUE TITLE
Open story in new tab button doesn't work 

### ISSUE THREAD

**Issue by sami616** [echoulen/storybook-addon-styled-component-theme#34]
Clicking on the icon at the top of storybook that opens the component on its own in a new tab doesn't seem to work when using this module.

**Comment by oudimms** [comment]
doesn't work for me as well, pls check

**Comment by schoenbergeringo** [comment]
+1

**Comment by Teicha** [comment]
+1

**Comment by echoulen** [comment]
which version of storybook use?
this is the map of storybook and addon
5.1 -> 1.2.4
5.0 -> 1.2.1
4.x -> 1.1.0

**Comment by sami616** [comment]
i'm `5.1 -> 1.2.4` at the moment but i still had the issue when i was on  `5.1 -> 1.2.4`

**Comment by echoulen** [comment]
I will check this issue later

**Comment by sami616** [comment]
Thanks for your work on this PR @echoulen. This unfortunately is still not working for me after upgrading. Anyone else?

**Comment by schoenbergeringo** [comment]
yes also still not working for me :/

**Comment by ojkelly** [comment]
I've found an issue like this relating to the following code  at https://github.com/echoulen/storybook-addon-styled-component-theme/blob/master/src/Themes.tsx#L67

```
    branch<BaseComponentProps>(
        ({active}) => !active,
        renderNothing,
    ),
```

It appears to be blocking render when a component is viewed via `iframe.html`

**Comment by ojkelly** [comment]
I also think in the case of viewing via an iframe (say for visual regression testing with loki), it would be nice to set the default theme, probably in `withThemeProvider`

**Comment by sami616** [comment]
Cool @ojkellie, or if @echoulen is adverse to adding another option to the API it could possible just use the first passed theme in the array?

**Comment by ojkelly** [comment]
I'm totally cool for using the first one passed.

I'm currently patching the issue with the following in `config.js` and using `NODE_ENV=test` in visual testing.

```
if (process.env.NODE_ENV === "test") {
  addDecorator(storyFn => (
    <ThemeProvider theme={Light}>{storyFn()}</ThemeProvider>
  ));
} else {
  addDecorator(withThemesProvider(themes));
}
```
