### ISSUE TITLE
use this addon for angular 6+ apps

### ISSUE THREAD

**Issue by WuglyakBolgoink** [echoulen/storybook-addon-styled-component-theme#4]
Hallo guys!

how can I add this addon for angular apps?

I need to switch between global multiple customer themes like `customer-main-light.css` and `customer-main-dark.css`, because we don't write a styles for components separate. 

Is possible with this addon? 

If I see example, u use only global props with custom props in component...

**Comment by echoulen** [comment]
The addon only for styled-component, switch `.css` the file is wired, I close it.

**Comment by WuglyakBolgoink** [comment]
ok
