### ISSUE TITLE
CustomProvider not working as expected 

### ISSUE THREAD

**Issue by hems** [echoulen/storybook-addon-styled-component-theme#49]
I'm trying to use this `addon` to switch between themes on `ChakraProvider` ( from http://next.chakra-ui.com/ ) but for some unknown reason my Chakra Component doesn't seem to be aware of the `Provider`.

I have written a pretty detailed explanation of my [implementation here](https://github.com/chakra-ui/chakra-ui/issues/2190#issuecomment-710344022).

Is there any extra steps needed in order to make it work?

Maybe i have implemented the CustomProvider wrong?

**Comment by echoulen** [comment]
CustomProvider is not support yet

**Comment by hems** [comment]
> CustomProvider is not supported yet

What do you mean by "is not supported yet" during my tests it seems to be working fine except for this little problem which seems to be specifically related to Chakra implementation?

What else needs to further implemented in this addon in order to consider it to be "supported"?

**Comment by echoulen** [comment]
I have long time no using Next js, may you create a PR to support this or ref to https://github.com/echoulen/storybook-addon-styled-component-theme/issues/32
