### ISSUE TITLE
Theme selection button set to 'serif'

### ISSUE THREAD

**Issue by saneef** [echoulen/storybook-addon-styled-component-theme#5]
![screenshot 2018-10-15 at 4 36 09 pm](https://user-images.githubusercontent.com/81863/46947470-8af94b00-d098-11e8-9b4b-7b30b80b84c6.png)

The font for the buttons are not set, so set to 'serif'. I'm using `@storybook/react v3.4.11`.

Can I create a PR to set the `font-family`?

**Comment by echoulen** [comment]
np
