### ISSUE TITLE
Support for storybook ^6.1.0 version

### ISSUE THREAD

**Issue by miguelangeltorresfp** [echoulen/storybook-addon-styled-component-theme#51]
Hi, just to report that this library doesn't seem to work with the latest version of storybook.

I'm currently using the last version of storybook-addon-styled-component-theme which is 1.3.0 with storybook version 6.0.26 and everything works perfectly.

But when I upgrade to any storybook version after 6.1.0 the themes don't change correctly. 

Thank you for this useful addon.

**Comment by echoulen** [comment]
ok, I will check

**Comment by yuriincentro** [comment]
any update on this yet??

**Comment by echoulen** [comment]
done, I will release new version
