### ISSUE TITLE
Themes showing up in every addon tab

### ISSUE THREAD

**Issue by Impirioxus** [echoulen/storybook-addon-styled-component-theme#7]
Themes are showing up at the bottom of every addon tab instead of just in the themes tab. Not sure if it's a bug or if I'm missing something. I managed to fix it by changing register.js and Themes.js but not sure if there's an easier way.

**Comment by echoulen** [comment]
change the import order in addons.js

**Comment by Impirioxus** [comment]
I tried changing the import order but it still displays it in every addon tab. It will display it at the bottom of every tab that comes before it in addons.js and at the top of every tab that comes after it.

**Comment by echoulen** [comment]
can you post the picture about this?

**Comment by Impirioxus** [comment]
This is my addons.js:

import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-viewport/register';
import '@storybook/addon-notes/register';
import 'storybook-addon-styled-component-theme/dist/register';
import '@storybook/addon-knobs/register';
import '@storybook/addon-a11y/register';
import '@storybook/addon-options/register';

I attached a picture of it at the top and at the bottom of an addon.
![top](https://user-images.githubusercontent.com/44717722/47967839-df587080-e02f-11e8-8399-dfe2df7740e3.png)
![bottom](https://user-images.githubusercontent.com/44717722/47967840-e0899d80-e02f-11e8-9c82-4cd74fdc17a0.png)
