### ISSUE TITLE
Theme Object Is Altered

### ISSUE THREAD

**Issue by Undistraction** [echoulen/storybook-addon-styled-component-theme#8]
I pass in an 'api' object with functions as part of my theme. So my theme looks something like this:
```
const theme = {
  ...
  api: {
    alpha: () => {}
    bravo: () => {}
  }
}
```

When using this addon, my `api` object is transformed to an empty object. When it is received by my components it now looks like this:
```
const theme = {
  ...
  api: {}
}
```

**Comment by echoulen** [comment]
looks like the styled component theme not working for `function` property

**Comment by Undistraction** [comment]
@echoulen functions are valid on themes. The problem is that this addon is altering the theme somehow.
